version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "text"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "andres-caylent/basic-app"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "devops-catalog"
    stage: "clone"

  # build:
  #   title: "Building Docker image"
  #   type: "build"
  #   image_name: "andres-caylent/basic-app"
  #   working_directory: "${{clone}}"
  #   tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
  #   dockerfile: "Dockerfile"
  #   stage: "build"

  # build:
  #   title: "Building container image"
  #   type: "build"
  #   arguments:
  #     working_directory: "${{clone}}"
  #     image_name: "lucerozuazquita/basic-app"
  #     tags:
  #     - ${{CF_SHORT_REVISION}}
  #     registry: docker-hub
  #     dockerfile: "Dockerfile"
  #   stage: build    

  blah:
    title: Running docker image
    type: freestyle
    #working_directory: ''
    working_directory: "${{clone}}"
    arguments:
      image: 'alpine:3.8'
      commands:
        - echo "blah"
        - echo "This is the pipeline in folder1/folder2"
    stage: text        